### ISSUE TITLE
所有噪声水平都共用一个模型吗？还是不同的噪声水平对应不同的模型？

### ISSUE THREAD

**Issue by aduyaoyao** [FanChiMao/SUNet#10]

**Comment by FanChiMao** [comment]
我們的訓練集是以DIV2K中隨機裁切後，隨機加上5~50的高斯雜訊程度，並沒有針對不同噪声水平獨立訓練不同的模型。
即提供的預訓練模型為**盲去噪(non-blind denoising)**，但由於是隨機加入噪声，會有部分噪声水平因訓練資料的些微差距導致效果較差(如: TABLE 1 中可以觀察到σ=10的分數較其他方法差)。

**Comment by aduyaoyao** [comment]
感谢你的回复，因为我最近在复现您的这篇论文。在加入噪声的部分，我看到matlab中的噪声加入的是固定的噪声水平，所以才会向您提问，看这篇的结果是否是在8000张图片上做的盲去噪。

**Comment by FanChiMao** [comment]
您好! 訓練集使用DIV2K train (800張) 隨機裁切[100張補丁](https://github.com/FanChiMao/SUNet/blob/e4f38eb7cd0dd5bfe20a5c861696768baff837b3/datasets/DIV2K_noise.m#L16)，並加入[隨機噪声](https://github.com/FanChiMao/SUNet/blob/e4f38eb7cd0dd5bfe20a5c861696768baff837b3/datasets/DIV2K_noise.m#L24-L25)。
而驗證集我們是用DIV2K test (100張)，加入[特定噪声(σ=10, 30, 50)](https://github.com/FanChiMao/SUNet/blob/e4f38eb7cd0dd5bfe20a5c861696768baff837b3/datasets/DIV2K_noise_val.m#L25-L30)，共300張。
故我們是訓練於80000張隨機雜訊圖像，驗證300張，使用GTX 1080Ti 訓練約耗時2個禮拜🥲。

**Comment by aduyaoyao** [comment]
太感谢你了，谢谢您的回复
