### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by Ajie-GitHub** [FanChiMao/SUNet#11]
Hello, thank you for your contribution on SUNet, I have the following error when I run the code, have you encountered it？ and if so, how to solve it, thank you again!

Questions are as follows:

==> Training start: 
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    psnr_val_rgb = torch.stack(psnr_val_rgb).mean().item()
RuntimeError: stack expects a non-empty TensorList

**Comment by FanChiMao** [comment]
Hello, according to your message, the psnr_val_rgb is empty value.

I guess your [validation images](https://github.com/FanChiMao/SUNet/blob/899f191ecaefcf28a9d2dca4849999cc9022cb78/training.yaml#L42) are not place correctly, maybe you can double-check it.

If you still encounter the same problem, feel free to contact me again!

**Comment by Ajie-GitHub** [comment]
Thanks for the tip, I checked my dataset file, but found it was not misplaced. The dataset file is shown below:

datasets
  └── Denoising_DIV2K
       ├── test
        |     ├── input     （100 images）
        |     └── target    （empty）
       └── train
             ├── input        （800 images）
             └── target       （empty）

Did you place your dataset this way as well?

**Comment by FanChiMao** [comment]
Oh, you have to first generate the training pair of DIV2K by the codes of [DIV2K_noise.m](https://github.com/FanChiMao/SUNet/blob/main/datasets/DIV2K_noise.m) and [DIV2K_noise_val.m](https://github.com/FanChiMao/SUNet/blob/main/datasets/DIV2K_noise_val.m).

The images in `input` folder are the noisy images (Noise), 
and the images in `target` folder are the noise-free images (GT).

The `test` folder denotes the validation, you can also refer the [**issue**](https://github.com/FanChiMao/SUNet/issues/4#issuecomment-1068064507) to generate training data.

If the `target` folder is empty, the model can't calculate the loss value between GT and restored images.

In our experiments, after generating the data, total image numbers are as following:

## Tree  
  ```
  datasets
    └── Denoising_DIV2K
         ├── test
         |     ├── input (900)
         |     └── target (900)   
         └── train
               ├── input (80000)
               └── target (80000)

  ```

**Comment by Ajie-GitHub** [comment]
Oh, thanks, the project is running, thanks again for your contribution!
