### ISSUE TITLE
您好，我想跑一个任意尺寸的噪声图片，但是没有找到预训练模型，请问预训练模型/pretrained_model/denoising_model.pth在哪里可以下载？

### ISSUE THREAD

**Issue by xie-pixel** [FanChiMao/SUNet#12]

**Comment by FanChiMao** [comment]
您好，若您仔細閱讀[README.md](https://github.com/FanChiMao/SUNet/blob/main/README.md)可發現[pretrained model連結](https://drive.google.com/file/d/1ViJgcFlKm1ScEoQH616nV4uqFhkg8J8D/view?usp=sharing)~，或是GitHub page的右側[Releases](https://github.com/FanChiMao/SUNet/releases/tag/0.0)也能下載。 下載後再將預訓練模型放置[設定](https://github.com/FanChiMao/SUNet/blob/899f191ecaefcf28a9d2dca4849999cc9022cb78/demo_any_resolution.py#L29-L31)的資料夾位置即可。

**Comment by xie-pixel** [comment]
好的，非常感谢您，非常有帮助
