### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by xie-pixel** [FanChiMao/SUNet#13]
![dd8681923377f14dbaa4f590e777d4f](https://user-images.githubusercontent.com/101094151/192680951-f65a51f0-5877-41ed-9c75-908a06acac17.jpg)
![f09570091cc35f876d54896157481dd](https://user-images.githubusercontent.com/101094151/192680995-361cab72-258a-4195-82b4-90c2e9e96b84.jpg)
![91ff3ab24ffc521dd90aad047143a8d](https://user-images.githubusercontent.com/101094151/192681006-cb2ccf5a-5c1c-4fb4-95c3-595ed35891dd.jpg)
![b2d349434732af375ec0284fa59a0e4](https://user-images.githubusercontent.com/101094151/192681035-111f6991-0220-470e-93cb-80f8b265d9bb.jpg)
![eea0c5ecf036b9c1d947580a1236523](https://user-images.githubusercontent.com/101094151/192681115-fc2cd79f-2ca4-4eda-b5a1-993a2e9ea05e.jpg)
Hello, @FanChiMao
I'm really sorry to bother you again, but I do have some problems that I can't solve by myself. I downloaded your pre-training weight awgn_denoising_sunet. PTH, captured a 256x256 image (boy.png), and tried to run demo.py to see the denoising effect. It was found that the image after denoising was consistent with the original image. I was very confused but could not find the problem. I am looking forward to your help.I am running on the window, whether this will have an impact？

**Comment by FanChiMao** [comment]
![Imgur](https://i.imgur.com/Sc3hwVA.png) ![Imgur](https://i.imgur.com/v9UttBB.png)  
![Imgur](https://i.imgur.com/XD1e1bz.png) ![Imgur](https://i.imgur.com/LRtayVe.png)  

Hello, @xie-pixel 

I try the demo.py and test on the crop of boy.jpg as you (I usually call him baby.png😂).
However, I get the pleasure results on both resizing and cropping to the image size of 256x256.
I think it is caused from the different generated methods of Gaussian noise. 
I follow the generated [**approach**](https://github.com/JavierGurrola/RDUNet/blob/549fc88c6faef1b310773944fc3988e22030d94d/Datasets/generate_test_dataset_color.m#L21-L25) of RDUNet, DHDN and DIDN, 
some well-known models like DnCNN, IrCNN and FFDNet etc. are generated by the [**KAIR**](https://github.com/cszn/KAIR) toolbox.
If you want to reproduce the results, you can see the generated [**codes**](https://github.com/FanChiMao/SUNet/tree/main/datasets) improved from RDUNet.

Hope this can help you, and have a nice day!

**Comment by xie-pixel** [comment]
@FanChiMao Thank you very much. I just tested your Bady. PNG and got good results. I had a very good day and I hope you have good luck too
