### ISSUE TITLE
测试相关

### ISSUE THREAD

**Issue by nnzs9248** [FanChiMao/SUNet#3]
如果我想测试任意尺寸的图片，需要改哪些参数吗

**Comment by FanChiMao** [comment]
您好:
如[README.md](https://github.com/FanChiMao/SUNet/blob/main/README.md)中Quick Run節中提到:

確認
--input_dir: 含有測試圖片的資料夾,
--result_dir: 去噪完的圖像結果資料夾,
--weights: 含有預訓[練權重檔](https://github.com/FanChiMao/SUNet/releases/download/0.0/AWGN_denoising_SUNet.pth)的位置,
以上都正確直接跑`demo_any_resolution.py` 即可。

若欲測試圖像較少，可以直接考慮用[Hugging Face](https://huggingface.co/spaces/52Hz/SUNet_AWGN_denoising)產生結果圖，缺點是只能使用CPU跑測試，輸入圖像太大張會花費較多時間。

**Comment by nnzs9248** [comment]
你好，还想请教一下，您的工程是在pytorch哪个版本下实现的？

**Comment by nnzs9248** [comment]
感谢你的解答

发自我的iPhone
