### ISSUE TITLE
RuntimeError: shape '[1, 64, 64, 96]' is invalid for input of size 24576

### ISSUE THREAD

**Issue by ChidanandKumarKS** [FanChiMao/SUNet#5]
@FanChiMao 
when i ran your model file SUnet_detail.py with test code in main function i got error below
RuntimeError: shape '[1, 64, 64, 96]' is invalid for input of size 24576.

Kindly requesting you to help me in this bug fix issue

https://github.com/FanChiMao/SUNet/blob/30eeb03395a9e275a5700914dfec0b71d12eb613/model/SUNet_detail.py#L234

**Comment by FanChiMao** [comment]
According your proposed messages, I guess you would like to evaluate the input image with the size of 1x3x64x64 for calculating FLOPs of SUNet. If so, I guess you should correct the parameter "[img_size](https://github.com/FanChiMao/SUNet/blob/30eeb03395a9e275a5700914dfec0b71d12eb613/model/SUNet_detail.py#L773)" from 256 to 64, because transformer needs a fixed mask to generate relevant q, k and v, our SUNet also has same limitation about this.

If you still face some problems, I will try to help!
Maybe you can supply more detail information about the bugs next time. 😄

**Comment by zhangbaijin** [comment]
I also have the problem, and my test dataset is (640,480), is it should be resized to 256x256 by myself?

**Comment by FanChiMao** [comment]
@zhangbaijin 

Hello, if you just want to evaluate the FLOPs and parameters, it has to test on 256x256 images (square).

Or you simply want to demonstrate the visual performance of your own dataset, the `demo_any_resolution.py` using window sliding method can be applied for any images.

**Comment by xie-pixel** [comment]
您好，@FanChiMao,我这边也遇到了这个问题，RuntimeError: shape '[1, 64, 64, 96]' is invalid for input of size 98304，请问是要到哪里修改[img_size]?是到training.yaml还是要到SUNET_detail.py修改 
        H, W = self.input_resolution
        B, L, C = x.shape
        print(H, W, B, L, C)
        # assert L == H * W, "input feature has wrong size"

        shortcut = x
        x = self.norm1(x)
        x = x.view(B, H, W, C)
这里的L我没有搞清楚这个意思，我这边输入的图片是[1,1,128,128]
非常期待得到您的帮助

**Comment by xie-pixel** [comment]
我的输入为torch.Size([1, 1, 128, 128])
这个网络期待输入的x = x.view(B,H,W,C)是[1, 64, 64, 96]

**Comment by xie-pixel** [comment]
> 

Have you solved the problem? Can we talk about it?

**Comment by FanChiMao** [comment]
@xie-pixel 
您好, 首先跑SUNET_detail.py是為了計算模型的複雜度，若你想測試輸入torch.Size([1, 1, 128, 128])的SUNet模型複雜度，SUNET_details.py應改為下列:

***
    height = 128
    width = 128
    x = torch.randn((1, 1, height, width))  # .cuda()
    model = SUNet(img_size=128, patch_size=4, in_chans=1, out_chans=1,
                  embed_dim=96, depths=[8, 8, 8, 8],
                  num_heads=[8, 8, 8, 8],
                  window_size=8, mlp_ratio=4., qkv_bias=True, qk_scale=2,
                  drop_rate=0., attn_drop_rate=0., drop_path_rate=0.1,
                  norm_layer=nn.LayerNorm, ape=False, patch_norm=True,
                  use_checkpoint=False, final_upsample="Dual up-sample")  # .cuda()
***

training.yaml的IMG_SIZE及其他參數是為了train.py建構出整體模型訓練而獨立提出來的。

**Comment by xie-pixel** [comment]
@FanChiMao 非常感谢您的帮助
