### ISSUE TITLE
stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by wangli926454** [FanChiMao/SUNet#6]
psnr_val_rgb = torch.stack(psnr_val_rgb).mean().item()
RuntimeError: stack expects a non-empty TensorList

Helllo author,I had an error running the train.py and I don't konw how to slove this problem. Can you help me ? 
thanks a lot

**Comment by wangli926454** [comment]
My torch is 1.6.0 +cu101 and my torchvision is 0.7.0

**Comment by FanChiMao** [comment]
According to your messages, I guess that error is caused about the validation images.
You have to check the following points:
1. The validation path: `VAL_DIR` is correct in `training.yaml`.
2. If the correct input/target sub-folder under above validation path?
3. The validation image pairs are correctly below in input/target sub-folder.
